/*
 * This source file was generated by the Gradle 'init' task
 */
package fi.tuni.tamk.tiko.wahalailkka;

import fi.tuni.tamk.tiko.wahalailkka.controller.PersonController;
import fi.tuni.tamk.tiko.wahalailkka.repository.MemPersonRepository;
import fi.tuni.tamk.tiko.wahalailkka.ui.Cli;

public final class App {
    private App() { }

    /**
     * Main method to run the application.
     *
     * @param args command line arguments (not used)
     */
    public static void main(final String[] args) {
        Cli cli = new Cli(new PersonController(new MemPersonRepository()));
        cli.run();
    }
}
